apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "project.fullname" . }}-failedNotify-cron-job
spec:
  schedule: "0 0 12 * * ?"
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: registry.pinsvc.net/ops/buildpack-deps:curl
              args:
                - /bin/sh
                - -ec
                - curl 'http://{{ template "project.fullname" . }}:{{ .Values.service.port }}/failedNotify'
          restartPolicy: OnFailure
