apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "project.fullname" . }}
  labels:
    app: {{ template "project.fullname" . }}
    chart: {{ template "project.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: {{ template "project.fullname" . }}
